rpc:
  host: 0.0.0.0
  port: 2203
  token: ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW
governance:
  timeoutMillSeconds: 0
registrycenter:
  connectionStrings: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183;127.0.0.1:2184,127.0.0.1:2185,127.0.0.1:2186
  type: Zookeeper
  scheme: Digest
  auth: "silky:pass4W0rd"
distributedCache:
  redis:
    isEnabled: true
    configuration: 127.0.0.1:6379,defaultDatabase=0
rabbitMq:
  host: 127.0.0.1
  port: 5672
  userName: rabbitmq
  password: rabbitmq
  virtualHost: /
  
connectionStrings:
  default: server=127.0.0.1;port=3306;database=Silky.Log;uid=root;pwd=qwe!P4ss;
  
plugInSource:
  modulePlugIn:
    types:
      - Silky.Log.EntityFrameworkCore.LogEfCoreModule,Silky.Log.EntityFrameworkCore 