nacosConfig:
  listeners:
    - optional: false
      dataId: silky.hero.nacos.basicdata
      group: DEV_GROUP
      appName: basicdata
    - optional: false
      dataId: silky.hero.nacos.common
      group: DEV_GROUP