nacosConfig:
  listeners:
    - optional: true
      dataId: silky.hero.nacos.saas
      group: DEV_GROUP
      appName: saas
    - optional: true
      dataId: silky.hero.nacos.common
      group: DEV_GROUP
  serverAddresses:
    - http://127.0.0.1:8848/
    - http://127.0.0.1:8849/
    - http://127.0.0.1:8850/
  userName: nacos
  password: nacos
  namespace: silky_config