// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Silky.WorkFlow.EntityFrameworkCore.DbContexts;

#nullable disable

namespace Silky.WorkFlow.Database.Migrations.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20221216111023_20221216v1")]
    partial class _20221216v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Silky.WorkFlow.Domain.BusinessCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BusinessCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("BusinessCode");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("BusinessName");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("BusinessCategory", (string)null);
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.FlowNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BusinessCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("BusinessCode");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FlowNodeCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("FlowNodeCode");

                    b.Property<string>("FlowNodeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("FlowNodeName");

                    b.Property<long>("NodeTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("NodeTypeId");

                    b.Property<string>("NodeValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NodeValue");

                    b.Property<string>("NodeVariable")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NodeVariable");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("NodeTypeId");

                    b.ToTable("FlowNode", (string)null);
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.NodeActionResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BusinessCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("BusinessCode");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FlowNodeCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("FlowNodeCode");

                    b.Property<long>("FlowNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("FlowNodeId");

                    b.Property<string>("NextFlowNodeCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NextFlowNodeCode");

                    b.Property<string>("NextFlowNodeId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NextFlowNodeId");

                    b.Property<int>("NodeAction")
                        .HasColumnType("int")
                        .HasColumnName("NodeAction");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FlowNodeId");

                    b.ToTable("NodeActionResult", (string)null);
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.NodeType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NodeTypeCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NodeTypeCode");

                    b.Property<string>("NodeTypeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NodeTypeName");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("NodeType", (string)null);
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.WorkFlowNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BusinessCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("BusinessCode");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FlowNodeCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("FlowNodeCode");

                    b.Property<string>("FlowNodeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NodeAction")
                        .HasColumnType("int")
                        .HasColumnName("NodeAction");

                    b.Property<int>("NodeStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2)
                        .HasColumnName("NodeStatus");

                    b.Property<long>("NodeTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("NodeTypeId");

                    b.Property<string>("NodeValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NodeValue");

                    b.Property<string>("NodeVariable")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NodeVariable");

                    b.Property<long>("PreviousId")
                        .HasColumnType("bigint")
                        .HasColumnName("PreviousId");

                    b.Property<long>("ProofId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProofId");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("NodeTypeId");

                    b.ToTable("WorkFlow", (string)null);
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.WorkFlowNodeActionResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BusinessCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("BusinessCode");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FlowNodeCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("FlowNodeCode");

                    b.Property<string>("NextFlowNodeCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NextFlowNodeCode");

                    b.Property<string>("NextFlowNodeId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NextFlowNodeId");

                    b.Property<int>("NodeAction")
                        .HasColumnType("int")
                        .HasColumnName("NodeAction");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("WorkFlowId")
                        .HasColumnType("bigint")
                        .HasColumnName("WorkFlowId");

                    b.HasKey("Id");

                    b.HasIndex("WorkFlowId");

                    b.ToTable("WorkFlowNodeActionResult", (string)null);
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.FlowNode", b =>
                {
                    b.HasOne("Silky.WorkFlow.Domain.NodeType", "NodeType")
                        .WithMany("FlowNodes")
                        .HasForeignKey("NodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NodeType");
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.NodeActionResult", b =>
                {
                    b.HasOne("Silky.WorkFlow.Domain.FlowNode", "FlowNode")
                        .WithMany("NextFlowNodes")
                        .HasForeignKey("FlowNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowNode");
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.WorkFlowNode", b =>
                {
                    b.HasOne("Silky.WorkFlow.Domain.NodeType", "NodeType")
                        .WithMany("WorkFlows")
                        .HasForeignKey("NodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NodeType");
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.WorkFlowNodeActionResult", b =>
                {
                    b.HasOne("Silky.WorkFlow.Domain.WorkFlowNode", "WorkFlow")
                        .WithMany("NextFlowNodes")
                        .HasForeignKey("WorkFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkFlow");
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.FlowNode", b =>
                {
                    b.Navigation("NextFlowNodes");
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.NodeType", b =>
                {
                    b.Navigation("FlowNodes");

                    b.Navigation("WorkFlows");
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.WorkFlowNode", b =>
                {
                    b.Navigation("NextFlowNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
