// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Silky.WorkFlow.EntityFrameworkCore.DbContexts;

#nullable disable

namespace Silky.WorkFlow.Database.Migrations.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20221220085604_202212201655init")]
    partial class _202212201655init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Silky.WorkFlow.Domain.BusinessCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BusinessCategoryCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("BusinessCategoryCode");

                    b.Property<string>("BusinessCategoryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("BusinessCategoryName");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("BusinessCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BusinessCategoryCode = "0",
                            BusinessCategoryName = "系统值",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.FlowNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BusinessCategoryCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("BusinessCategoryCode");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FlowNodeCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("FlowNodeCode");

                    b.Property<string>("FlowNodeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("FlowNodeName");

                    b.Property<long>("NodeTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("NodeTypeId");

                    b.Property<string>("NodeValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NodeValue");

                    b.Property<string>("NodeVariable")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NodeVariable");

                    b.Property<int>("StepNo")
                        .HasColumnType("int")
                        .HasColumnName("StepNo");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("NodeTypeId");

                    b.ToTable("FlowNode", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BusinessCategoryCode = "0",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FlowNodeCode = "0",
                            FlowNodeName = "终节点",
                            NodeTypeId = 1L,
                            NodeValue = "",
                            NodeVariable = "",
                            StepNo = -1
                        });
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.NodeActionResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BusinessCategoryCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("BusinessCategoryCode");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("FlowNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("FlowNodeId");

                    b.Property<int>("NodeAction")
                        .HasColumnType("int")
                        .HasColumnName("NodeAction");

                    b.Property<long>("PrevFlowNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("PrevFlowNodeId");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FlowNodeId");

                    b.ToTable("NodeActionResult", (string)null);
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.NodeType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NodeTypeCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NodeTypeCode");

                    b.Property<string>("NodeTypeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NodeTypeName");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("NodeType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NodeTypeCode = "0",
                            NodeTypeName = "系统节点"
                        });
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.WorkFlowNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BusinessCategoryCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("BusinessCategoryCode");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FlowNodeCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("FlowNodeCode");

                    b.Property<string>("FlowNodeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("FlowNodeName");

                    b.Property<int>("NodeStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("NodeStatus");

                    b.Property<long>("NodeTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("NodeTypeId");

                    b.Property<string>("NodeValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NodeValue");

                    b.Property<string>("NodeVariable")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NodeVariable");

                    b.Property<long>("PreviousId")
                        .HasColumnType("bigint")
                        .HasColumnName("PreviousId");

                    b.Property<long>("ProofId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProofId");

                    b.Property<int>("StepNo")
                        .HasColumnType("int")
                        .HasColumnName("StepNo");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("NodeTypeId");

                    b.ToTable("WorkFlow", (string)null);
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.WorkFlowNodeActionResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BusinessCategoryCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("BusinessCategoryCode");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NodeAction")
                        .HasColumnType("int")
                        .HasColumnName("NodeAction");

                    b.Property<long>("PrevWorkFlowId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProofId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProofId");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("WorkFlowId")
                        .HasColumnType("bigint")
                        .HasColumnName("WorkFlowId");

                    b.HasKey("Id");

                    b.HasIndex("WorkFlowId");

                    b.ToTable("WorkFlowNodeActionResult", (string)null);
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.FlowNode", b =>
                {
                    b.HasOne("Silky.WorkFlow.Domain.NodeType", "NodeType")
                        .WithMany("FlowNodes")
                        .HasForeignKey("NodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NodeType");
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.NodeActionResult", b =>
                {
                    b.HasOne("Silky.WorkFlow.Domain.FlowNode", "FlowNode")
                        .WithMany("NextNodes")
                        .HasForeignKey("FlowNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowNode");
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.WorkFlowNode", b =>
                {
                    b.HasOne("Silky.WorkFlow.Domain.NodeType", "NodeType")
                        .WithMany("WorkFlows")
                        .HasForeignKey("NodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NodeType");
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.WorkFlowNodeActionResult", b =>
                {
                    b.HasOne("Silky.WorkFlow.Domain.WorkFlowNode", "WorkFlow")
                        .WithMany("NextFlowNodes")
                        .HasForeignKey("WorkFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkFlow");
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.FlowNode", b =>
                {
                    b.Navigation("NextNodes");
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.NodeType", b =>
                {
                    b.Navigation("FlowNodes");

                    b.Navigation("WorkFlows");
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.WorkFlowNode", b =>
                {
                    b.Navigation("NextFlowNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
