// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Silky.WorkFlow.EntityFrameworkCore.DbContexts;

#nullable disable

namespace Silky.WorkFlow.Database.Migrations.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Silky.WorkFlow.Domain.BusinessCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BusinessCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("BusinessCode");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("BusinessName");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("BusinessCategory", (string)null);
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.NodeVariant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NodeType")
                        .HasColumnType("int")
                        .HasColumnName("NodeType");

                    b.Property<string>("NodeValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("NodeValue");

                    b.Property<string>("NodeVariable")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("NodeVariable");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("NodeVariant", (string)null);
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.WorkFlow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint")
                        .HasColumnName("ActivityId");

                    b.Property<string>("BusinessCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("BusinessCode");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("NextId")
                        .HasColumnType("bigint")
                        .HasColumnName("NextId");

                    b.Property<int>("NodeAction")
                        .HasColumnType("int")
                        .HasColumnName("NodeAction");

                    b.Property<string>("NodeCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NodeCode");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NodeName");

                    b.Property<int>("NodeType")
                        .HasColumnType("int")
                        .HasColumnName("NodeType");

                    b.Property<string>("NodeValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("NodeValue");

                    b.Property<string>("NodeVariable")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("NodeVariable");

                    b.Property<long>("PreviousId")
                        .HasColumnType("bigint")
                        .HasColumnName("PreviousId");

                    b.Property<long>("ProofId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProofId");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("WorkFlow", (string)null);
                });

            modelBuilder.Entity("Silky.WorkFlow.Domain.WorkFlowNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BusinessCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("BusinessCode");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NodeAction")
                        .HasColumnType("int")
                        .HasColumnName("NodeAction");

                    b.Property<string>("NodeCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NodeCode");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NodeName");

                    b.Property<long>("NodeVariantId")
                        .HasColumnType("bigint")
                        .HasColumnName("NodeVariantId");

                    b.Property<int>("StepCode")
                        .HasColumnType("int")
                        .HasColumnName("StepCode");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("WorkFlowNode", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
