version: '3.7'

services:
  silky.account:
    image: silkyhero/account:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.Account/src/Silky.AccountHost/Dockerfile
    volumes:
      - ./logs/silky.account:/app/logs    
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-Development}
      rpc__token: ${rpc__token:-ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW}
      governance__timeoutMillSeconds: ${governance__timeoutMillSeconds:-5000}
      registrycenter__type: ${registrycenter__type:-Zookeeper}
      registrycenter__connectionStrings: ${registrycenter__connectionStrings:-silky.zoo1:2181,silky.zoo2:2181,silky.zoo3:2181;silky.zoo4:2181,silky.zoo5:2181,silky.zoo6:2181}
      distributedCache__redis__isEnabled: ${distributedCache__redis__isEnabled:-true}
      distributedCache__redis__configuration: ${distributedCache__redis__configuration:-silky.redis:6379,defaultDatabase=0}
      connectionStrings__default:  ${connectionStrings__account:-server=silky.mysql;port=3306;database=silky.account;uid=root;pwd=qwe!P4ss;}
      skyWalking__transport__gRPC__servers: ${skyWalking__transport__gRPC__servers:-oap:11800}
    networks: 
      - silky_service_net

  silky.basicdata:
    image: silkyhero/basicdata:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.BasicData/src/Silky.BasicDataHost/Dockerfile
    volumes:
      - ./logs/silky.basicdata:/app/logs    
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-Development}
      rpc__token: ${rpc__token:-ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW}
      governance__timeoutMillSeconds: ${governance__timeoutMillSeconds:-5000}
      registrycenter__type: ${registrycenter__type:-Zookeeper}
      registrycenter__connectionStrings: ${registrycenter__connectionStrings:-silky.zoo1:2181,silky.zoo2:2181,silky.zoo3:2181;silky.zoo4:2181,silky.zoo5:2181,silky.zoo6:2181}
      distributedCache__redis__isEnabled: ${distributedCache__redis__isEnabled:-true}
      distributedCache__redis__configuration: ${distributedCache__redis__configuration:-silky.redis:6379,defaultDatabase=0}
      connectionStrings__default:  ${connectionStrings__basicdata:-server=silky.mysql;port=3306;database=silky.basicdata;uid=root;pwd=qwe!P4ss;}
      skyWalking__transport__gRPC__servers: ${skyWalking__transport__gRPC__servers:-oap:11800}
    networks: 
      - silky_service_net
    
  silky.identity:
    image: silkyhero/identity:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.Identity/src/Silky.IdentityHost/Dockerfile
    volumes:
      - ./logs/silky.identity:/app/logs    
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-Development}
      rpc__token: ${rpc__token:-ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW}
      governance__timeoutMillSeconds: ${governance__timeoutMillSeconds:-5000}
      registrycenter__type: ${registrycenter__type:-Zookeeper}
      registrycenter__connectionStrings: ${registrycenter__connectionStrings:-silky.zoo1:2181,silky.zoo2:2181,silky.zoo3:2181;silky.zoo4:2181,silky.zoo5:2181,silky.zoo6:2181}
      distributedCache__redis__isEnabled: ${distributedCache__redis__isEnabled:-true}
      distributedCache__redis__configuration: ${distributedCache__redis__configuration:-silky.redis:6379,defaultDatabase=0}
      connectionStrings__default:  ${connectionStrings__identity:-server=silky.mysql;port=3306;database=silky.identity;uid=root;pwd=qwe!P4ss;}
      skyWalking__transport__gRPC__servers: ${skyWalking__transport__gRPC__servers:-oap:11800}
    networks: 
      - silky_service_net
    
  silky.log:
    image: silkyhero/log:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.Log/src/Silky.LogHost/Dockerfile
    volumes:
      - ./logs/silky.log:/app/logs    
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-Development}
      rpc__token: ${rpc__token:-ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW}
      governance__timeoutMillSeconds: ${governance__timeoutMillSeconds:-5000}
      registrycenter__type: ${registrycenter__type:-Zookeeper}
      registrycenter__connectionStrings: ${registrycenter__connectionStrings:-silky.zoo1:2181,silky.zoo2:2181,silky.zoo3:2181;silky.zoo4:2181,silky.zoo5:2181,silky.zoo6:2181}
      distributedCache__redis__isEnabled: ${distributedCache__redis__isEnabled:-true}
      distributedCache__redis__configuration: ${distributedCache__redis__configuration:-silky.redis:6379,defaultDatabase=0}
      connectionStrings__default:  ${connectionStrings__log:-server=silky.mysql;port=3306;database=silky.log;uid=root;pwd=qwe!P4ss;}
      skyWalking__transport__gRPC__servers: ${skyWalking__transport__gRPC__servers:-oap:11800}
      rabbitMq__host: ${rabbitMq__host:-silky.rabbitmq}
      rabbitMq__port: ${rabbitMq__host:-5672}
      rabbitMq__userName: ${rabbitMq__userName:-rabbitmq}
      rabbitMq__password: ${rabbitMq__password:-rabbitmq}
      rabbitMq__virtualHost: ${rabbitMq__virtualHost:-/}
    networks: 
      - silky_service_net
      
  silky.organization:
    image: silkyhero/organization:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.Organization/src/Silky.OrganizationHost/Dockerfile
    volumes:
      - ./logs/silky.organization:/app/logs    
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-Development}
      rpc__token: ${rpc__token:-ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW}
      governance__timeoutMillSeconds: ${governance__timeoutMillSeconds:-5000}
      registrycenter__type: ${registrycenter__type:-Zookeeper}
      registrycenter__connectionStrings: ${registrycenter__connectionStrings:-silky.zoo1:2181,silky.zoo2:2181,silky.zoo3:2181;silky.zoo4:2181,silky.zoo5:2181,silky.zoo6:2181}
      distributedCache__redis__isEnabled: ${distributedCache__redis__isEnabled:-true}
      distributedCache__redis__configuration: ${distributedCache__redis__configuration:-silky.redis:6379,defaultDatabase=0}
      connectionStrings__default:  ${connectionStrings__organization:-server=silky.mysql;port=3306;database=silky.organization;uid=root;pwd=qwe!P4ss;}
      skyWalking__transport__gRPC__servers: ${skyWalking__transport__gRPC__servers:-oap:11800}
    networks: 
      - silky_service_net
      
  silky.permission:
    image: silkyhero/permission:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.Permission/src/Silky.PermissionHost/Dockerfile
    volumes:
      - ./logs/silky.permission:/app/logs    
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-Development}
      rpc__token: ${rpc__token:-ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW}
      governance__timeoutMillSeconds: ${governance__timeoutMillSeconds:-5000}
      registrycenter__type: ${registrycenter__type:-Zookeeper}
      registrycenter__connectionStrings: ${registrycenter__connectionStrings:-silky.zoo1:2181,silky.zoo2:2181,silky.zoo3:2181;silky.zoo4:2181,silky.zoo5:2181,silky.zoo6:2181}
      distributedCache__redis__isEnabled: ${distributedCache__redis__isEnabled:-true}
      distributedCache__redis__configuration: ${distributedCache__redis__configuration:-silky.redis:6379,defaultDatabase=0}
      connectionStrings__default:  ${connectionStrings__permission:-server=silky.mysql;port=3306;database=silky.permission;uid=root;pwd=qwe!P4ss;}
      skyWalking__transport__gRPC__servers: ${skyWalking__transport__gRPC__servers:-oap:11800}
    networks: 
      - silky_service_net
    
  silky.position:
    image: silkyhero/position:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.Position/src/Silky.PositionHost/Dockerfile
    volumes:
      - ./logs/silky.position:/app/logs    
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-Development}
      rpc__token: ${rpc__token:-ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW}
      governance__timeoutMillSeconds: ${governance__timeoutMillSeconds:-5000}
      registrycenter__type: ${registrycenter__type:-Zookeeper}
      registrycenter__connectionStrings: ${registrycenter__connectionStrings:-silky.zoo1:2181,silky.zoo2:2181,silky.zoo3:2181;silky.zoo4:2181,silky.zoo5:2181,silky.zoo6:2181}
      distributedCache__redis__isEnabled: ${distributedCache__redis__isEnabled:-true}
      distributedCache__redis__configuration: ${distributedCache__redis__configuration:-silky.redis:6379,defaultDatabase=0}
      connectionStrings__default:  ${connectionStrings__position:-server=silky.mysql;port=3306;database=silky.position;uid=root;pwd=qwe!P4ss;}
      skyWalking__transport__gRPC__servers: ${skyWalking__transport__gRPC__servers:-oap:11800}
    networks: 
      - silky_service_net
    
  silky.saas:
    image: silkyhero/saas:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.Saas/src/Silky.SaasHost/Dockerfile
    volumes:
      - ./logs/silky.saas:/app/logs    
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-Development}
      rpc__token: ${rpc__token:-ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW}
      governance__timeoutMillSeconds: ${governance__timeoutMillSeconds:-5000}
      registrycenter__type: ${registrycenter__type:-Zookeeper}
      registrycenter__connectionStrings: ${registrycenter__connectionStrings:-silky.zoo1:2181,silky.zoo2:2181,silky.zoo3:2181;silky.zoo4:2181,silky.zoo5:2181,silky.zoo6:2181}
      distributedCache__redis__isEnabled: ${distributedCache__redis__isEnabled:-true}
      distributedCache__redis__configuration: ${distributedCache__redis__configuration:-silky.redis:6379,defaultDatabase=0}
      connectionStrings__default:  ${connectionStrings__saas:-server=silky.mysql;port=3306;database=silky.saas;uid=root;pwd=qwe!P4ss;}
      skyWalking__transport__gRPC__servers: ${skyWalking__transport__gRPC__servers:-oap:11800}
    networks: 
      - silky_service_net
    
  silky.gateway:
    image: silkyhero/gateway:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.Gateway/src/Silky.GatewayHost/Dockerfile
    volumes:
      - ./logs/silky.gateway:/app/logs    
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-Development}
      rpc__token: ${rpc__token:-ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW}
      governance__timeoutMillSeconds: ${governance__timeoutMillSeconds:-5000}
      registrycenter__type: ${registrycenter__type:-Zookeeper}
      registrycenter__connectionStrings: ${registrycenter__connectionStrings:-silky.zoo1:2181,silky.zoo2:2181,silky.zoo3:2181;silky.zoo4:2181,silky.zoo5:2181,silky.zoo6:2181}
      distributedCache__redis__isEnabled: ${distributedCache__redis__isEnabled:-true}
      distributedCache__redis__configuration: ${distributedCache__redis__configuration:-silky.redis:6379,defaultDatabase=0}
      connectionStrings__default:  ${connectionStrings__order:-server=silky.mysql;port=3306;database=order;uid=root;pwd=qwe!P4ss;}
      skyWalking__transport__gRPC__servers: ${skyWalking__transport__gRPC__servers:-oap:11800}
      rabbitMq__host: ${rabbitMq__host:-silky.rabbitmq}
      rabbitMq__port: ${rabbitMq__host:-5672}
      rabbitMq__userName: ${rabbitMq__userName:-rabbitmq}
      rabbitMq__password: ${rabbitMq__password:-rabbitmq}
      rabbitMq__virtualHost: ${rabbitMq__virtualHost:-/}
      healthChecksUI__healthChecks__0__name: silkyrpc
      healthChecksUI__healthChecks__0__uri: http://silky.gateway/silkyrpc/healthz
    networks: 
      - silky_service_net
    ports:
      - 8080:80
networks:
  silky_service_net: 
    external:
      name: silky_service_net