rpc:
  host: 0.0.0.0
  port: 2200
  token: ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW
governance:
  timeoutMillSeconds: 0
registrycenter:
  connectionStrings: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183;127.0.0.1:2184,127.0.0.1:2185,127.0.0.1:2186
  type: Zookeeper
  scheme: Digest
  auth: "silky:pass4W0rd"
distributedCache:
  redis:
    isEnabled: true
    configuration: 127.0.0.1:6379,defaultDatabase=0
connectionStrings:
  default: server=127.0.0.1;port=3306;database=Silky.Identity;uid=root;pwd=qwe!P4ss;
jwtSettings:
  secret: jv1PZkwjLVCEygM7faLLvEhDGWmFqRUW