nacosConfig:
  listeners:
    - optional: false
      dataId: silky.hero.nacos.workFlow
      group: PRO_GROUP
      appName: workFlow
    - optional: false
      dataId: silky.hero.nacos.common
      group: PRO_GROUP