nacosConfig:
  listeners:
    - optional: false
      dataId: silky.hero.nacos.position
      group: DEV_GROUP
      appName: position
    - optional: false
      dataId: silky.hero.nacos.common
      group: DEV_GROUP