nacosConfig:
  listeners:
    - optional: false
      dataId: silky.hero.nacos.gateway
      group: DEV_GROUP
      appName: gateway
    - optional: false
      dataId: silky.hero.nacos.common
      group: DEV_GROUP